#!/usr/bin/env bash
# clean.sh — reset baby-app to inputs-only state.
#
# Keeps hand-written specs (idea.md, PRD.md, data-models.md, navigations.json),
# pubspec.yaml, .converge/ playbook source, and assets/assets.json.
# Wipes every generated artifact so the next `./scripts/run.sh` rebuilds clean.
#
# Usage:
#   ./scripts/clean.sh                 # full reset
#   ./scripts/clean.sh --dry-run       # show what would be removed
#   ./scripts/clean.sh --keep-stitch   # preserve .stitch/ (expensive to regen)
#   ./scripts/clean.sh --keep-ide      # preserve .idea/ + *.iml

set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DRY=0
KEEP_STITCH=0
KEEP_IDE=0
for a in "$@"; do
  case "$a" in
    --dry-run|--dry) DRY=1 ;;
    --keep-stitch)   KEEP_STITCH=1 ;;
    --keep-ide)      KEEP_IDE=1 ;;
    -h|--help)
      sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "unknown flag: $a (use --help)" >&2
      exit 2
      ;;
  esac
done

# Safety net: only run inside a baby-app workspace.
if [ ! -f "$ROOT/.converge/project.yml" ] || [ ! -f "$ROOT/idea.md" ]; then
  echo "refusing to clean: $ROOT does not look like a baby-app workspace" >&2
  echo "  (expected .converge/project.yml and idea.md)" >&2
  exit 1
fi

say() {
  local target="$1"
  if [ ! -e "$target" ] && [ ! -L "$target" ]; then
    return
  fi
  if [ "$DRY" -eq 1 ]; then
    echo "DRY  rm -rf $target"
  else
    rm -rf "$target"
    echo "rm   ${target#$ROOT/}"
  fi
}

say_glob() {
  local pat="$1"
  # shellcheck disable=SC2206
  local matches=( $pat )
  for m in "${matches[@]}"; do
    [ -e "$m" ] || continue
    say "$m"
  done
}

echo "=== baby-app: clean ($([ "$DRY" -eq 1 ] && echo "dry-run" || echo "real")) ==="

# 1. Flutter build + dependency caches.
say "$ROOT/lib"
say "$ROOT/build"
say "$ROOT/.dart_tool"
say "$ROOT/.flutter-plugins-dependencies"
say "$ROOT/pubspec.lock"

# 2. Platform scaffolds (regenerated by `flutter create` if needed).
for plat in macos android ios web linux windows; do
  say "$ROOT/$plat"
done

# 3. Generated design + asset artifacts.
if [ "$KEEP_STITCH" -eq 0 ]; then
  say "$ROOT/.stitch"
fi
say_glob "$ROOT/assets/illustrations/*"
say_glob "$ROOT/assets/icons/*"
say_glob "$ROOT/assets/images/*"

# 4. Default Flutter test scaffold (re-created by 09-generate-tests).
say "$ROOT/test/widget_test.dart"

# 5. Converge runtime state — keep .converge/playbooks/, .converge/skills/, .converge/project.yml.
say "$ROOT/.converge/journal"
say "$ROOT/.converge/inventory"
say "$ROOT/.converge/checkpoints"
say "$ROOT/.converge/cache"
say "$ROOT/.converge/artifacts"

# 6. IDE detritus.
if [ "$KEEP_IDE" -eq 0 ]; then
  say "$ROOT/.idea"
  say_glob "$ROOT"/*.iml
fi

# 7. Sanity check post-conditions in real mode.
if [ "$DRY" -eq 0 ]; then
  echo ""
  echo "=== post-conditions ==="
  for f in idea.md PRD.md data-models.md navigations.json pubspec.yaml .converge/project.yml assets/assets.json; do
    if [ -e "$ROOT/$f" ]; then
      echo "  keep   $f"
    else
      echo "  MISS   $f (input was missing before clean ran)" >&2
    fi
  done
  for f in lib pubspec.lock build .dart_tool; do
    if [ -e "$ROOT/$f" ]; then
      echo "  STAY   $f (still present — investigate)" >&2
    fi
  done
fi
